export enum RESULT_STATUS {
  FAILED = 0,
  SUCCEED = 1,
}
export enum TYPE_PIC {
  PROFILE = 0,
  BACKGROUND = 1,
}
export const IS_VERIFIED = true;
export const REQUEST_ID_TOKEN_HEADER = 'x-request-id';
export const FORWARDED_FOR_TOKEN_HEADER = 'x-forwarded-for';
export const VERIFICATION_TIME = 5; //minutes
export const MESSAGES = {
  REPORT_RESPONSE_NOT_FOUND: 'report_response_not_found',
  REPORT_NOT_FOUND: 'report_not_found',
  USER_SAVED_THIS_POST: 'user_saved_this_post',
  POST_NOT_SAVED: 'post_not_saved',
  CAN_NOT_FOLLOW_YOUR_SELF: 'can_not_follow_your_self',
  FOLLOWED_USER_NOT_FOUND: 'followed_user_not_found',
  FOLLOWER_NOT_FOUND: 'follower_not_found',
  CAN_NOT_REVIEW_MULTIPLE_TIME: 'can_not_review_multiple_time',
  CAN_NOT_REVIEW_POST_HAVE_NOT_RECEIVED:
    'can_not_review_post_have_not_received',
  USER_REGISTERED_THIS_POST: 'user_registered_this_post',
  CAN_NOT_DELETE_OTHER_USER_REVIEW: 'can_not_delete_other_user_review',
  CAN_NOT_DELETE_OTHER_USER_POST_REGISTRATION:
    'can_not_delete_other_user_post_registration',
  CAN_NOT_DELETE_OTHER_USER_COMMENT: 'can_not_delete_other_user_comment',
  CAN_NOT_DELETE_OTHER_USER_POST: 'can_not_delete_other_user_post',
  CAN_NOT_DELETE_OTHER_USER_REACTION: 'can_not_delete_other_user_reaction',
  USER_REACTION_EXIST: 'user_reaction_exist',
  TYPE_NOT_FOUND: 'type_not_found',
  REVIEW_NOT_FOUND: 'review_not_found',
  CAN_NOT_REGISTER_YOUR_OWN_POST: 'can_not_register_your_own_post',
  POST_REGISTRATION_NOT_FOUND: 'post_registration_not_found',
  COMMENT_NOT_FOUND: 'comment_not_found',
  POST_NOT_FOUND: 'post_not_found',
  POST_NOT_FOUND_IN_TRASH_BIN: 'post_not_found_in_trash_bin',
  CATEGORY_NOT_FOUND: 'category_not_found',
  CATEGORY_NOT_FOUND_IN_TRASH_BIN: 'category_not_found_in_trash_bin',
  CATEGORY_NAME_EXIST: 'category_name_exist',
  VERIFICATION_CODE_NOT_EXPIRED: 'verification_code_not_expired',
  SEND_MAIL_SUCCESSFULLY: 'send_mail_successfully',
  VERIFICATION_INCORRECT: 'verification_incorrect',
  VERIFICATION_EXPIRED: 'verification_expired',
  USER_VERIFIED: 'user_verified',
  GET_SUCCEED: 'get_succeed',
  CREATED_SUCCEED: 'created_succeed',
  DELETED_SUCCEED: 'deleted_succeed',
  UPLOADED_SUCCEED: 'uploaded_succeed',
  UPDATE_SUCCEED: 'update_succeed',
  UPDATED_OR_DELETED_SUCCEED: 'updated_or_deleted_succeed',
  CREATED_OR_UPDATED_SUCCEED: 'updated_or_created_succeed',
  EMAIL_NOT_FOUND: `email_not_found`,
  NOT_FOUND_USER: 'not_found_user',
  WRONG_EMAIL_FORMAT: 'wrong_email_format',
  WRONG_PHONE_NUMBER_FORMAT: 'wrong_phone_number_format',
  PHONE_NUMBER_EXISTS: 'phone_number_exists',
  EMAIL_EXISTS: 'email_exists',
  USER_NAME_EXISTS: 'user_name_exists',
  PROVINCE_NOT_EXISTS: 'province_not_exists',
  DISTRICT_NOT_EXISTS: 'district_not_exists',
  WARD_NOT_EXISTS: 'ward_not_exists',
  IMPORT_SUCCESSFUL: 'import_successfully',
  IMPORT_FAILED: 'import_failed',
  UNAUTHORIZED: 'unauthorized',
  INCORRECT_PASSWORD: 'incorrect_password',
  UNCONFIRMED_ACCOUNT: 'unconfirmed_account',
  ACTION_NOT_PERFORMED: 'action_not_performed',
  ROLE_NOT_FOUND: 'role_not_found',
};
export const MAIL_TEMPLATE = {
  VERIFY_EMAIL_TEMPLATE: 'verify-email',
  SIGNUP_SUCCESSFULLY_EMAIL_TEMPLATE: 'signup-successfully-email',
  FORGOT_PASSWORD_TEMPLATE: 'forgot-password-email',
  UPDATE_EMAIL_TEMPLATE: 'update-email',
  VERIFY_FORGOT_EMAIL_TEMPLATE: 'verify-forgot-email',
};
